# A: Start from the node base image
FROM node:22

# TODO: Set a working directory inside the container (hint: /app)

# TODO: Copy local files into the image

# TODO: Execute npm install

# TODO: Set the default command to start your Node.js app (hint: node index.js)